# Generated by Django 4.2.4 on 2023-09-21 11:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contacts", "0001_squashed_0003_rename_pone_contact_phone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="phone",
            field=models.CharField(max_length=21),
        ),
    ]
