# Generated by Django 4.2.4 on 2023-09-29 18:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contacts", "0004_alter_contact_phone"),
    ]

    operations = [
        migrations.CreateModel(
            name="Group",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("value", models.CharField(max_length=100, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name="contact",
            options={"ordering": ["-modified_at", "name"]},
        ),
        migrations.AddField(
            model_name="contact",
            name="colors",
            field=models.ManyToManyField(related_name="animals", to="contacts.group"),
        ),
    ]
