# Generated by Django 4.2.4 on 2023-09-29 18:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contacts", "0005_group_alter_contact_options_contact_colors"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contact",
            name="phone",
        ),
        migrations.AddField(
            model_name="contact",
            name="birthday",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
